- hosts: all 
  gather_facts: true
  vars:
    wake_server: localhost
    macaddress: "{{ (ansible_interfaces|first).macaddress|default(mac|default('')) }}"

  tasks:
  - name: wake up machines.
    include: tasks/wol.yaml
  - name: install steam.
    win_chocolatey:
      name: steam
      state: present
  - name: install epic games launcher.
    win_chocolatey:
      name: epicgameslauncher
      state: present