# - name: start 7 Days to Die container
#   when: ACTION=="7daysstart"
#   docker_container:
#     name: 7d2d
#     image: zobees/7daystodie
#     state: started
#     restart_policy: unless-stopped
#     env:
#       PGID: "1000"
#       PUID: "1000"
#       CONFIG_FILE: "fokisserverconfig.xml"
#       QUERY_PORT: "26901"
#     volumes:
#     - /home/josh/configs/7daystodie/:/data
#     ports:
#      - 8001:8001
#      - 8002:8002
#      - 26900-26902:26900-26902
#      - 26900-26902:26900-26902/udp

- name: Check for players
  # when: Empty=="False"
  vars:
    secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33353661376631623162313266336332343063393862626361383031313936623536346532656266
          3539343832666535633333663235633238373361653761610a343732313832343063643166636162
          62306230653662623365663637643964323739366439653936353835633766383131393263333831
          3130303062373432380a333131353236336166303166643239656531333961376235383036306230
          3231
  telnet:
    # host: localhost
    login_prompt: "Please enter password:"
    # user: ""
    port: 8001
    user: "{{ secret }}"
    command: 
      - listplayers
      # - exit
  register: telnet_out

- name: parse output
  debug: 
    msg: "{{telnet_out.stdout_lines}}"
  #when: telnet_out.stdout_lines=="Total of 0 in the game"
  #register: Empty=="True"

# - name: stop 7 Days to Die container
#   when: ACTION=="7daysstart"
#   docker_container:
#     name: 7d2d
#     image: zobees/7daystodie
#     state: stopped
#     restart_policy: unless-stopped
#     env:
#       PGID: "1000"
#       PUID: "1000"
#       CONFIG_FILE: "fokisserverconfig.xml"
#       QUERY_PORT: "26901"
#     volumes:
#     - /home/josh/configs/7daystodie/:/data
#     ports:
#      - 8001:8001
#      - 8002:8002
#      - 26900-26902:26900-26902
#      - 26900-26902:26900-26902/udp

# - name: update 7 Days to Die container
#   when: ACTION=="7daysupdate"
#   docker_container:
#     name: 7d2d
#     image: zobees/7daystodie
#     pulle: yes
#     restart: yes
#     state: started
#     restart_policy: unless-stopped
#     env:
#       PGID: "1000"
#       PUID: "1000"
#       CONFIG_FILE: "fokisserverconfig.xml"
#       QUERY_PORT: "26901"
#     volumes:
#     - /home/josh/configs/7daystodie/:/data
#     ports:
#      - 8001:8001
#      - 8002:8002
#      - 26900-26902:26900-26902
#      - 26900-26902:26900-26902/udp