---
- name: Verify backup location is created
  when: ACTION=="backup" or ACTION=="new-world"
  file:
    dest: /media/c/girls-mc-server/
    state: directory

- name: Add version to file
  when: ACTION=="upgrade"
  lineinfile:
    path: /home/josh/configs/girls-mc-server/version
    create: yes
    regexp: "^\\d\\.\\d\\d.*$"
    line: "{{version}}"

- name: Archive world to generate new-world
  when: ACTION=="new-world" or ACTION=="backup"
  archive:
   format: tar
   path: 
   - /home/josh/configs/girls-mc-server/world*
   - /home/josh/configs/girls-mc-server/banned-ips.json
   - /home/josh/configs/girls-mc-server/banned-players.json
   - /home/josh/configs/girls-mc-server/commands.yml
   - /home/josh/configs/girls-mc-server/config
   - /home/josh/configs/girls-mc-server/config.json
   - /home/josh/configs/girls-mc-server/DiscordConsole.log
   - /home/josh/configs/girls-mc-server/eula.txt
   - /home/josh/configs/girls-mc-server/help.yml
   - /home/josh/configs/girls-mc-server/ops.json
   - /home/josh/configs/girls-mc-server/paper.yml
   - /home/josh/configs/girls-mc-server/permissions.yml
   - /home/josh/configs/girls-mc-server/server.properties
   - /home/josh/configs/girls-mc-server/spigot.yml
   - /home/josh/configs/girls-mc-server/usercache.json
   - /home/josh/configs/girls-mc-server/version_history.json
   - /home/josh/configs/girls-mc-server/whitelist.json
   dest: "/media/c/girls-mc-server/girls-mc-backup-{{ ansible_date_time.iso8601_basic }}.tar"

# - name: Clean Minecraft folder
#   when: ACTION=="new-world"
#   file:
#     path: /home/josh/configs/girls-mc-server/world/
#     state: absent

# - name: Clean Minecraft folder
#   when: ACTION=="new-world"
#   file:
#     path: /home/josh/configs/girls-mc-server/world_nether/
#     state: absent

# - name: Clean Minecraft folder
#   when: ACTION=="new-world"
#   file:
#     path: /home/josh/configs/girls-mc-server/world_the_end/
#     state: absent

- name: Get Current version
  when: ACTION=="restart" or ACTION=="new-world"
  shell: cat /home/josh/configs/girls-mc-server/version
  register: version
  
    

# - name: Restart a container
#   when: ACTION=="restart" or ACTION=="new-world"
#   docker_container:
#     name: girls-mc-server
#     image: itzg/minecraft-server
#     state: started
#     pull: true
#     restart: yes
#     restart_policy: unless-stopped
#     ports:
#      - 25565:25565
#     command: "--noconsole"
#     env:
#         PGID: "1000"
#         PUID: "1000"
#         TZ: "America/Chicago"
#         EULA: TRUE
#         TYPE: PAPER
#         VERSION: "{{ version.stdout.currentVersion }}"
#     volumes:
#      - /home/josh/configs/girls-mc-server/:/data

# - name: Check Version Availability
#   shell: "/opt/scripts/papermccheck.py -v {{ version }}"
#   when: ACTION=="update"

# - name: Update Version of Minecraft
#   when: ACTION=="upgrade" and FOUND=="True"
#   docker_container:
#     name: girls-mc-server
#     image: itzg/minecraft-server
#     state: started
#     pull: true
#     restart: yes
#     restart_policy: unless-stopped
#     ports:
#      - 25565:25565
#     command: "--noconsole"
#     env:
#         PGID: "1000"
#         PUID: "1000"
#         TZ: "America/Chicago"
#         EULA: TRUE
#         TYPE: PAPER
#         VERSION: "{{ version }}"
#     volumes:
#      - /home/josh/configs/girls-mc-server/:/data
